on:
  push:
    branches:
    - main

jobs:
  UpdatePost:
    runs-on: ubuntu-latest
    steps:
      - name: Read README.md
        id: mainReadMe
        uses: jaywcjlove/github-action-read-file@main
        with:
          branch: main
          path: README.md

      - name: Echo README.md(gh-pages)
        run: echo "${{ steps.mainReadMe.outputs.content }}"
  
      - name: Login
        id: Login
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ env.LEMMY_URL }}"
          data: '{"username_or_email":"${{ env.LEMMY_USER }}","password":"${{ secrets.LEMMY_PASSWORD }}"}'

      - name: print3
        run: echo "{'name':'${{ env.POST_TITLE }}','body':'${{ steps.mainReadMe.outputs.content }}','nsfw':false,'post_id':${{ env.POST_ID }},'language_id':0,'auth':'${{ fromJson(steps.Login.outputs.response).jwt }}'}"
    
      - name: HTTP Request Action
        # You may pin to the exact commit or the version.
        # uses: fjogeleit/http-request-action@eab8015483ccea148feff7b1c65f320805ddc2bf
        uses: satak/webrequest-action@master
        with:
          # Request URL
          url: "${{ env.LEMMY_URL }}"
          # Request Method
          method: "PUT"
          # Content Type
          contentType: "application/json"
          # Request Body as JSON String
          payload: |
            {"name":"${{ env.POST_TITLE }}","body":${{ toJson(steps.mainReadMe.outputs.content) }},"nsfw":false,"post_id":${{ env.POST_ID }},"language_id":0,"auth":"${{ fromJson(steps.Login.outputs.response).jwt }}"}
          
