name: Update communities
on:
  push:
    branches:
    - main

jobs:
  run:
    name: Update communities
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
       with:
         repository: 'fnic-lemmy/bestofbot'
         fetch-depth: 0
         path: './bestofbot/'

     - uses: actions/checkout@v4
       with:
         repository: 'fnic-lemmy/lemmy-directory'
         path: './directory/'
            
     - run: |
         cd ./directory
         ./scripts/directory_to_json.py
         cp ./_fnic_comms.json ../bestofbot/
         cp ./_anime_comms.json ../bestofbot/

     - name: Create PR
       uses: peter-evans/create-pull-request@v6
       with:
         token: ${{ secrets.TOKEN }}
         path: './bestofbot'
         branch: 'community-updates'
         base: 'main'
         commit-message: '[automated] Update community lists'
         title: '[automated] Update community lists'
         body: 'Update community lists generated automatically'
         delete-branch: true
           
